In [1]:
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

# Tensor Basics

In [2]:
# "scalar" or "rank-0" tensor . A scalar contains a single value, and no "axes".
rank0 = tf.constant(4)
print(rank0)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
# "vector" or "rank-1" tensor is like a list of values. A vector has 1-axis
rank1 = tf.constant([2.0, 3.0, 4.0])
print(rank1)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [4]:
# "matrix" or "rank-2" tensor has 2-axes
rank2 = tf.constant([[1, 2],
                     [2, 3],
                     [4, 5]], dtype=tf.float16)
print(rank2)

tf.Tensor(
[[1. 2.]
 [2. 3.]
 [4. 5.]], shape=(3, 2), dtype=float16)


In [5]:
# tensor with 3-axes
array = np.arange(15).reshape(3, 1, 5)
rank3 = tf.convert_to_tensor(array)
print(rank3)

tf.Tensor(
[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]], shape=(3, 1, 5), dtype=int64)


In [6]:
# convert to numpy using np.array() or tf.numpy()
r2_array = np.array(rank2)
print(np.allclose(r2_array, rank2.numpy()))

True


In [7]:
# basic math operations
x = tf.constant([[1, 2],
                 [3, 4]])
y = tf.ones([2, 2], dtype=tf.int32)
print('X:    Y:')
print(x[0, :].numpy(), y[0, :].numpy())
print(x[1, :].numpy(), y[1, :].numpy(), '\n')
print('Adding:\n', tf.add(x, y), '\n')
print('Element-wise Multiplication:\n', tf.multiply(x, y), '\n')
print('Matrix Multiplication:\n', tf.matmul(x, y))

X:    Y:
[1 2] [1 1]
[3 4] [1 1] 

Adding:
 tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

Element-wise Multiplication:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

Matrix Multiplication:
 tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [8]:
print('x + y == tf.add(x, y) --> ', np.allclose(tf.add(x, y), x + y))
print('x * y == tf.multiply(x, y) --> ', np.allclose(tf.multiply(x, y), x * y))
print('x @ y == tf.matmul(x, y) --> ', np.allclose(tf.matmul(x, y), x @ y))

x + y == tf.add(x, y) -->  True
x * y == tf.multiply(x, y) -->  True
x @ y == tf.matmul(x, y) -->  True


In [9]:
# basic tensor ops
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
print('Largest Value:', tf.reduce_max(c))
print('Index of Largest Value:', tf.argmax(c))
print('Softmax:\n', tf.nn.softmax(c))

Largest Value: tf.Tensor(10.0, shape=(), dtype=float32)
Index of Largest Value: tf.Tensor([1 0], shape=(2,), dtype=int64)
Softmax:
 tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


# Shapes

In [10]:
tensor = tf.zeros([3, 2, 4, 5])

In [11]:
print('Data type:', tensor.dtype)
print('Number of dimensions:', tensor.ndim)
print('Shape of tensor:', tensor.shape)
print('Total number of elements:', tf.size(tensor).numpy())

Data type: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (3, 2, 4, 5)
Total number of elements: 120


In [12]:
print('Elements along axis 0:\n', tensor.shape[0])

Elements along axis 0:
 3


In [13]:
print('Elements along last axis of tensor:\n', tensor.shape[-1])

Elements along last axis of tensor:
 5


# Single-axis Indexing

In [14]:
t = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(t.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


In [15]:
# indexing with scalar
print(t[0].numpy(), t[1].numpy(), t[-1].numpy())

0 1 34


In [16]:
# indexing with colon
print('Everything:', t[:].numpy())
print('Before 4:', t[:4].numpy())
print('From 4 to end:', t[4:].numpy())
print('From 2, before 7:', t[2:7].numpy())
print('Every other item:', t[::2].numpy())
print('Reversed:', t[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


# Multi-axis Indexing

In [17]:
t = tf.constant([[1, 2], [3, 4], [5, 6]])
print(t)
print('Rank:', tf.rank(t).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Rank: 2


In [18]:
# index single value
print(t[1, 1].numpy())

4


In [19]:
# combination of ints and slices
print('Second Row:', t[1, :].numpy())
print('Second Column:', t[:, 1].numpy())
print('Last Row:', t[-1, :].numpy())
print('First item in last column:', t[0, -1].numpy())
print('Skip the first row:\n', t[1:, :].numpy())

Second Row: [3 4]
Second Column: [2 4 6]
Last Row: [5 6]
First item in last column: 2
Skip the first row:
 [[3 4]
 [5 6]]


In [20]:
# rank 3 tensor
print(rank3[:, :, 4])

tf.Tensor(
[[ 4]
 [ 9]
 [14]], shape=(3, 1), dtype=int64)
